const DATA_ID = "@DATA/";

const DATA_CALL = `${DATA_ID}DATA_CALL_`;

export const DATA_CALL_EPISODES = `${DATA_CALL}EPISODES`;
export const DATA_CALL_EPISODE = `${DATA_CALL}EPISODE`;
export const DATA_CALL_CHARACTERS = `${DATA_CALL}CHARACTERS`;
export const DATA_CALL_CHARACTER = `${DATA_CALL}CHARACTER`;
export const DATA_CALL_QUOTES = `${DATA_CALL}QUOTES`;
export const DATA_CALL_QUOTE = `${DATA_CALL}QUOTE`;
export const DATA_CALL_DEATHS = `${DATA_CALL}DEATHS`;

const DATA_RESPONSE = `${DATA_ID}DATA_RESPONSE_`;

export const DATA_RESPONSE_EPISODES = `${DATA_RESPONSE}EPISODES`;
export const DATA_RESPONSE_EPISODE = `${DATA_RESPONSE}EPISODE`;
export const DATA_RESPONSE_CHARACTERS = `${DATA_RESPONSE}CHARACTERS`;
export const DATA_RESPONSE_CHARACTER = `${DATA_RESPONSE}CHARACTER`;
export const DATA_RESPONSE_QUOTES = `${DATA_RESPONSE}QUOTES`;
export const DATA_RESPONSE_QUOTE = `${DATA_RESPONSE}QUOTE`;
export const DATA_RESPONSE_DEATHS = `${DATA_RESPONSE}DEATHS`;

const DATA_ERROR = `${DATA_ID}DATA_ERROR_`;

export const DATA_ERROR_EPISODES = `${DATA_ERROR}EPISODES`;
export const DATA_ERROR_EPISODE = `${DATA_ERROR}EPISODE`;
export const DATA_ERROR_CHARACTERS = `${DATA_ERROR}CHARACTERS`;
export const DATA_ERROR_CHARACTER = `${DATA_ERROR}CHARACTER`;
export const DATA_ERROR_QUOTES = `${DATA_ERROR}QUOTES`;
export const DATA_ERROR_QUOTE = `${DATA_ERROR}QUOTE`;
export const DATA_ERROR_DEATHS = `${DATA_ERROR}DEATHS`;
