const DATA_ID = "@DATA/";

export const DATA_LOADING = `${DATA_ID}DATA_LOADING`;
export const DATA_ERROR = `${DATA_ID}DATA_ERROR`;

const DATA_RESPONSE = `${DATA_ID}DATA_RESPONSE_`;

export const DATA_RESPONSE_EPISODES = `${DATA_RESPONSE}EPISODES`;
export const DATA_RESPONSE_CHARACTERS = `${DATA_RESPONSE}CHARACTERS`;
export const DATA_RESPONSE_CHARACTER = `${DATA_RESPONSE}CHARACTER`;
export const DATA_RESPONSE_QUOTES = `${DATA_RESPONSE}QUOTES`;
export const DATA_RESPONSE_QUOTE = `${DATA_RESPONSE}QUOTE`;
export const DATA_RESPONSE_DEATHS = `${DATA_RESPONSE}DEATHS`;
